export const keys = {
  // 예시

  GET_MAIN: 'GET_MAIN',

  GET_POSTS: 'GET_POSTS',
  GET_TAG: 'GET_POST_ONE',
  GET_REPORT_FILE: 'GET_REPORT_FILE',
  GET_REQUEST_LIST: 'GET_REQUEST_LIST',
  GET_MYREQUEST: 'GET_MYREQUEST',
};
