export const COLOR = {
  VACATION_RED: '#E64042',
  SCHEDULE_BLUE: '#BADAFF',
  DETAIL_GRAY: '#D9D9D9',
  VACATION_BAR: '#E64042',
  VACATION_COLOR: '#FFFFFF',
  HALF_DAY_OFF_BOARD: '#DDDDDD',
  HALF_DAY_OFF_BAR: '#DDDDDD',
  MONTHLY_VACTION_BAR: '#1F1F1F',
  SICK_DAY_BAR: '#BADAFF',
  CONBANTION_BAR: '#1F1F1F',
  OTHER_BAR: '#DDDDDD',
  OTHER_BAR_BOARD: '#DDDDDD',
  BUSINESS_TRIP_BAR: '#BADAFF',
  MEETING_BAR: '#E64042',
  WHITE_COLOR: '#FFFFFF',
  MEETING_BAR: 'E64042',

  // 철환폰트
  PAGE_SPAN: '#484240',
  PAGE_DONE: '#A1A1A1',
  PAGE_BLUE: '#8AB2E0',
};
