export const COLOR = {
  VACATION_RED: '#E64042',
  SCHEDULE_BLUE: '#BADAFF',
  DETAIL_GRAY: '#D9D9D9',
  VACATION_BAR: '#E64042',
  VACATION_COLOR: '#FFFFFF',
  HALF_DAY_OFF_BOARD: '#DDDDDD',
  HALF_DAY_OFF_BAR: '#DDDDDD',
  MONTHLY_VACTION_BAR: '#1F1F1F',
  SICK_DAY_BAR: '#BADAFF',
  CONBANTION_BAR: '#1F1F1F',
  OTHER_BAR: '#DDDDDD',
  OTHER_BAR_BOARD: '#DDDDDD',
  BUSINESS_TRIP_BAR: '#BADAFF',
  MEETING_BAR: '#E64042',
  WHITE_COLOR: '#FFFFFF',

  // 철환폰트
  PAGE_SPAN: '#484240',
  PAGE_DONE: '#A1A1A1',
  PAGE_BLUE: '#8AB2E0',
  PAGE_LIGHTBLUE: '#BADAFF',
  PAGE_WHITE: '#FBF8F8',

  //Figma 기준
  FONT_COLOR: '#1F1F1F',
  FONT_3: '#484240',
  POINT_C: '#E64042',
  SUB: '#BADAFF',
  SUB1: '#8AB2E0',
  GRAY1: '#DDDDDD',
  GRAY2: '#A1A1A1',
  LIGHTGRAY: '#F6F6F6',
};
